# -*- coding: utf-8 -*-
"""Clean_Text_YouTube.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LIkxqSKKYmAD60m_1jypn5Ct2eLH0i8k
"""

import pandas as pd
import numpy as np
import nltk
import string
from nltk.corpus import stopwords
nltk.download('stopwords')

df = pd.read_csv("/content/Youtube_Reviews - Sheet1.csv")

def clean_text(text):
    if pd.isnull(text):
        return ""
    tokens = text.lower().translate(str.maketrans('', '', string.punctuation)).split()
    return ' '.join([word for word in tokens if word not in stopwords.words('english')])

df['Transcript_Cleaned'] = df['Transcript/Transcript Link'].apply(clean_text)
df.head()

df.to_csv('clean_text_youtube.csv')