# -*- coding: utf-8 -*-
"""glassdoor_cleaned

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19E6GhvPm0ncQwx4S7TI6upWyPNRUYlKd
"""

import pandas as pd

# Load the dataset
df = pd.read_csv('/content/drive/MyDrive/glassdoor_reviews - glass_reviews.csv')

# Preview the data
print(df.head())

# Get info about the columns
print(df.info())

# Check number of rows and columns
print(df.shape)

# Get statistical summary of numeric columns
print(df.describe())

df['company_name'].value_counts()

df.isnull().sum().sort_values(ascending=False)

df.nunique().sort_values()

df = df.drop(columns=['company_name', 'count_unhelpful', 'count_helpful', 'flag_covid', 'flag_featured', 'review_advice'])

df.head()
df.isnull().sum().sort_values(ascending=False)

df = df.dropna(subset=['summary', 'employee_status', 'employee_job_title'])
df.info()

df = df.drop_duplicates()

df.head()

df = df.drop(columns = ['summary'])

columns_to_process = ['flags_ceo_approval', 'flags_business_outlook', 'flags_recommend_frend', 'employee_status']

for col in columns_to_process:

    df[col] = df[col].astype(str).str.upper()

df.head()

df.to_csv('glassdoor_cleaned.csv', index = False)