# -*- coding: utf-8 -*-
"""Glassdoor_Cleaned_Text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DZH791oOumRtnmzEiMQKUspWdoGkvdzj
"""

import pandas as pd
import numpy as np
import nltk
import string
from nltk.corpus import stopwords
nltk.download('stopwords')

df = pd.read_csv("/content/drive/MyDrive/glassdoor_cleaned_V2.csv")

def clean_text(text):
    if pd.isnull(text):
        return ""
    tokens = text.lower().translate(str.maketrans('', '', string.punctuation)).split()
    return ' '.join([word for word in tokens if word not in stopwords.words('english')])

columns = ['advice_to_management', 'review_pros', 'review_cons']

for col in columns:
  df[col] = df[col].apply(clean_text)

df.head()

df.to_csv('/content/cleaned_glassdoor_reviews.csv', index=False)